import type {
  CanonicalIngredient,
  IngredientAlias,
  IngredientSubstitution,
  ProteinProduct,
  RetailerAvailabilityEvidence,
} from "@fitness-autopilot/contracts";
import { normalizeIngredientAlias } from "./normalize";

const TS = "2026-09-19T00:00:00.000Z";

/** Fixed UUIDs so SQL seed and TypeScript seed stay aligned. */
export const SEED_INGREDIENT_IDS = {
  chickenBreastBonelessSkinless: "c1000000-0000-4000-a000-000000000001",
  chickenThighBonelessSkinless: "c1000000-0000-4000-a000-000000000002",
  chickenThighBoneInSkinOn: "c1000000-0000-4000-a000-000000000003",
  chickenWings: "c1000000-0000-4000-a000-000000000004",
  groundChicken: "c1000000-0000-4000-a000-000000000005",
  groundTurkey937: "c1000000-0000-4000-a000-000000000006",
  groundBeef8020: "c1000000-0000-4000-a000-000000000007",
  groundBeef9010: "c1000000-0000-4000-a000-000000000008",
  groundBeef937: "c1000000-0000-4000-a000-000000000009",
  ribeyeSteak: "c1000000-0000-4000-a000-000000000010",
  nyStripSteak: "c1000000-0000-4000-a000-000000000011",
  topSirloinSteak: "c1000000-0000-4000-a000-000000000012",
  flankSteak: "c1000000-0000-4000-a000-000000000013",
  beefTenderloin: "c1000000-0000-4000-a000-000000000014",
  chuckRoast: "c1000000-0000-4000-a000-000000000015",
  beefStewMeat: "c1000000-0000-4000-a000-000000000016",
  atlanticSalmonFillet: "c1000000-0000-4000-a000-000000000017",
  codFillet: "c1000000-0000-4000-a000-000000000018",
  tilapiaFillet: "c1000000-0000-4000-a000-000000000019",
  shrimpPeeledDeveined: "c1000000-0000-4000-a000-000000000020",
  lobsterTail: "c1000000-0000-4000-a000-000000000021",
  largeChickenEggs: "c1000000-0000-4000-a000-000000000022",
  paneer: "c1000000-0000-4000-a000-000000000023",
  extraFirmTofu: "c1000000-0000-4000-a000-000000000024",
  cannedChickpeas: "c1000000-0000-4000-a000-000000000025",
  cookedLentils: "c1000000-0000-4000-a000-000000000026",
} as const;

export const SEED_PRODUCT_IDS = {
  chickenBreastBonelessSkinless: "c2000000-0000-4000-a000-000000000001",
  chickenThighBonelessSkinless: "c2000000-0000-4000-a000-000000000002",
  chickenThighBoneInSkinOn: "c2000000-0000-4000-a000-000000000003",
  chickenWings: "c2000000-0000-4000-a000-000000000004",
  groundChicken: "c2000000-0000-4000-a000-000000000005",
  groundTurkey937: "c2000000-0000-4000-a000-000000000006",
  groundBeef8020: "c2000000-0000-4000-a000-000000000007",
  groundBeef9010: "c2000000-0000-4000-a000-000000000008",
  groundBeef937: "c2000000-0000-4000-a000-000000000009",
  ribeyeSteak: "c2000000-0000-4000-a000-000000000010",
  nyStripSteak: "c2000000-0000-4000-a000-000000000011",
  topSirloinSteak: "c2000000-0000-4000-a000-000000000012",
  flankSteak: "c2000000-0000-4000-a000-000000000013",
  beefTenderloin: "c2000000-0000-4000-a000-000000000014",
  chuckRoast: "c2000000-0000-4000-a000-000000000015",
  beefStewMeat: "c2000000-0000-4000-a000-000000000016",
  atlanticSalmonFillet: "c2000000-0000-4000-a000-000000000017",
  codFillet: "c2000000-0000-4000-a000-000000000018",
  tilapiaFillet: "c2000000-0000-4000-a000-000000000019",
  shrimpPeeledDeveined: "c2000000-0000-4000-a000-000000000020",
  lobsterTail: "c2000000-0000-4000-a000-000000000021",
  largeChickenEggs: "c2000000-0000-4000-a000-000000000022",
  paneer: "c2000000-0000-4000-a000-000000000023",
  extraFirmTofu: "c2000000-0000-4000-a000-000000000024",
  cannedChickpeas: "c2000000-0000-4000-a000-000000000025",
  cookedLentils: "c2000000-0000-4000-a000-000000000026",
} as const;

function ingredient(
  id: string,
  canonicalKey: string,
  displayName: string,
  availabilityClass: CanonicalIngredient["availabilityClass"],
  extras: Partial<
    Pick<
      CanonicalIngredient,
      "defaultUnit" | "nutritionSourceType" | "nutritionSourceId" | "category"
    >
  > = {},
): CanonicalIngredient {
  return {
    id,
    canonicalKey,
    displayName,
    category: extras.category ?? "protein",
    defaultUnit: extras.defaultUnit ?? "g",
    availabilityClass,
    nutritionSourceType: extras.nutritionSourceType,
    nutritionSourceId: extras.nutritionSourceId,
    createdAt: TS,
    updatedAt: TS,
  };
}

function product(
  partial: Omit<ProteinProduct, "createdAt" | "updatedAt" | "active"> & { active?: boolean },
): ProteinProduct {
  return {
    ...partial,
    active: partial.active ?? true,
    createdAt: TS,
    updatedAt: TS,
  };
}

function alias(
  id: string,
  ingredientId: string,
  displayAlias: string,
): IngredientAlias {
  return {
    id,
    ingredientId,
    displayAlias,
    normalizedAlias: normalizeIngredientAlias(displayAlias),
  };
}

export const SEED_CANONICAL_INGREDIENTS: CanonicalIngredient[] = [
  ingredient(
    SEED_INGREDIENT_IDS.chickenBreastBonelessSkinless,
    "chicken_breast_boneless_skinless",
    "Boneless skinless chicken breast",
    "widely_available",
  ),
  ingredient(
    SEED_INGREDIENT_IDS.chickenThighBonelessSkinless,
    "chicken_thigh_boneless_skinless",
    "Boneless skinless chicken thighs",
    "widely_available",
  ),
  ingredient(
    SEED_INGREDIENT_IDS.chickenThighBoneInSkinOn,
    "chicken_thigh_bone_in_skin_on",
    "Bone-in skin-on chicken thighs",
    "commonly_available",
  ),
  ingredient(
    SEED_INGREDIENT_IDS.chickenWings,
    "chicken_wings",
    "Chicken wings",
    "widely_available",
  ),
  ingredient(
    SEED_INGREDIENT_IDS.groundChicken,
    "ground_chicken",
    "Ground chicken",
    "commonly_available",
  ),
  ingredient(
    SEED_INGREDIENT_IDS.groundTurkey937,
    "ground_turkey_93_7",
    "93/7 ground turkey",
    "widely_available",
  ),
  ingredient(
    SEED_INGREDIENT_IDS.groundBeef8020,
    "ground_beef_80_20",
    "80/20 ground beef",
    "widely_available",
  ),
  ingredient(
    SEED_INGREDIENT_IDS.groundBeef9010,
    "ground_beef_90_10",
    "90/10 ground beef",
    "widely_available",
  ),
  ingredient(
    SEED_INGREDIENT_IDS.groundBeef937,
    "ground_beef_93_7",
    "93/7 ground beef",
    "widely_available",
  ),
  ingredient(
    SEED_INGREDIENT_IDS.ribeyeSteak,
    "beef_ribeye_steak",
    "Ribeye steak",
    "commonly_available",
  ),
  ingredient(
    SEED_INGREDIENT_IDS.nyStripSteak,
    "beef_new_york_strip_steak",
    "New York strip steak",
    "commonly_available",
  ),
  ingredient(
    SEED_INGREDIENT_IDS.topSirloinSteak,
    "beef_top_sirloin_steak",
    "Top sirloin steak",
    "widely_available",
  ),
  ingredient(
    SEED_INGREDIENT_IDS.flankSteak,
    "beef_flank_steak",
    "Flank steak",
    "commonly_available",
  ),
  ingredient(
    SEED_INGREDIENT_IDS.beefTenderloin,
    "beef_tenderloin",
    "Beef tenderloin",
    "retailer_dependent",
  ),
  ingredient(
    SEED_INGREDIENT_IDS.chuckRoast,
    "beef_chuck_roast",
    "Chuck roast",
    "widely_available",
  ),
  ingredient(
    SEED_INGREDIENT_IDS.beefStewMeat,
    "beef_stew_meat",
    "Beef stew meat",
    "widely_available",
  ),
  ingredient(
    SEED_INGREDIENT_IDS.atlanticSalmonFillet,
    "atlantic_salmon_fillet",
    "Atlantic salmon fillet",
    "commonly_available",
  ),
  ingredient(
    SEED_INGREDIENT_IDS.codFillet,
    "cod_fillet",
    "Cod fillet",
    "commonly_available",
  ),
  ingredient(
    SEED_INGREDIENT_IDS.tilapiaFillet,
    "tilapia_fillet",
    "Tilapia fillet",
    "widely_available",
  ),
  ingredient(
    SEED_INGREDIENT_IDS.shrimpPeeledDeveined,
    "shrimp_raw_peeled_deveined",
    "Raw peeled and deveined shrimp",
    "widely_available",
  ),
  ingredient(
    SEED_INGREDIENT_IDS.lobsterTail,
    "lobster_tail",
    "Lobster tail",
    "specialty",
  ),
  ingredient(
    SEED_INGREDIENT_IDS.largeChickenEggs,
    "chicken_eggs_large",
    "Large chicken eggs",
    "widely_available",
    { defaultUnit: "count", category: "protein" },
  ),
  ingredient(
    SEED_INGREDIENT_IDS.paneer,
    "paneer",
    "Paneer",
    "commonly_available",
    { category: "dairy" },
  ),
  ingredient(
    SEED_INGREDIENT_IDS.extraFirmTofu,
    "tofu_extra_firm",
    "Extra-firm tofu",
    "widely_available",
  ),
  ingredient(
    SEED_INGREDIENT_IDS.cannedChickpeas,
    "chickpeas_canned",
    "Canned chickpeas",
    "widely_available",
    { category: "legume", defaultUnit: "g" },
  ),
  ingredient(
    SEED_INGREDIENT_IDS.cookedLentils,
    "lentils_cooked",
    "Cooked lentils",
    "widely_available",
    { category: "legume", defaultUnit: "g" },
  ),
];

export const SEED_PROTEIN_PRODUCTS: ProteinProduct[] = [
  product({
    id: SEED_PRODUCT_IDS.chickenBreastBonelessSkinless,
    canonicalKey: "chicken_breast_boneless_skinless",
    ingredientId: SEED_INGREDIENT_IDS.chickenBreastBonelessSkinless,
    proteinFamily: "chicken",
    displayName: "Boneless Skinless Chicken Breast",
    species: "chicken",
    cut: "breast",
    form: "whole_muscle",
    boneState: "boneless",
    skinState: "skinless",
    typicalPurchaseUnit: "lb",
    availabilityClass: "widely_available",
  }),
  product({
    id: SEED_PRODUCT_IDS.chickenThighBonelessSkinless,
    canonicalKey: "chicken_thigh_boneless_skinless",
    ingredientId: SEED_INGREDIENT_IDS.chickenThighBonelessSkinless,
    proteinFamily: "chicken",
    displayName: "Boneless Skinless Chicken Thighs",
    species: "chicken",
    cut: "thigh",
    form: "whole_muscle",
    boneState: "boneless",
    skinState: "skinless",
    typicalPurchaseUnit: "lb",
    availabilityClass: "widely_available",
  }),
  product({
    id: SEED_PRODUCT_IDS.chickenThighBoneInSkinOn,
    canonicalKey: "chicken_thigh_bone_in_skin_on",
    ingredientId: SEED_INGREDIENT_IDS.chickenThighBoneInSkinOn,
    proteinFamily: "chicken",
    displayName: "Bone-In Skin-On Chicken Thighs",
    species: "chicken",
    cut: "thigh",
    form: "whole_muscle",
    boneState: "bone_in",
    skinState: "skin_on",
    typicalPurchaseUnit: "lb",
    availabilityClass: "commonly_available",
  }),
  product({
    id: SEED_PRODUCT_IDS.chickenWings,
    canonicalKey: "chicken_wings",
    ingredientId: SEED_INGREDIENT_IDS.chickenWings,
    proteinFamily: "chicken",
    displayName: "Chicken Wings",
    species: "chicken",
    cut: "wing",
    form: "whole_muscle",
    boneState: "bone_in",
    skinState: "skin_on",
    typicalPurchaseUnit: "lb",
    availabilityClass: "widely_available",
  }),
  product({
    id: SEED_PRODUCT_IDS.groundChicken,
    canonicalKey: "ground_chicken",
    ingredientId: SEED_INGREDIENT_IDS.groundChicken,
    proteinFamily: "chicken",
    displayName: "Ground Chicken",
    species: "chicken",
    cut: "ground",
    form: "ground",
    boneState: "not_applicable",
    skinState: "not_applicable",
    // fatDescriptor intentionally omitted — not verified
    typicalPurchaseUnit: "lb",
    availabilityClass: "commonly_available",
  }),
  product({
    id: SEED_PRODUCT_IDS.groundTurkey937,
    canonicalKey: "ground_turkey_93_7",
    ingredientId: SEED_INGREDIENT_IDS.groundTurkey937,
    proteinFamily: "turkey",
    displayName: "93/7 Ground Turkey",
    species: "turkey",
    cut: "ground",
    form: "ground",
    boneState: "not_applicable",
    skinState: "not_applicable",
    fatDescriptor: "93/7",
    typicalPurchaseUnit: "lb",
    availabilityClass: "widely_available",
  }),
  product({
    id: SEED_PRODUCT_IDS.groundBeef8020,
    canonicalKey: "ground_beef_80_20",
    ingredientId: SEED_INGREDIENT_IDS.groundBeef8020,
    proteinFamily: "beef",
    displayName: "80/20 Ground Beef",
    species: "cattle",
    cut: "ground",
    form: "ground",
    boneState: "not_applicable",
    skinState: "not_applicable",
    fatDescriptor: "80/20",
    typicalPurchaseUnit: "lb",
    availabilityClass: "widely_available",
  }),
  product({
    id: SEED_PRODUCT_IDS.groundBeef9010,
    canonicalKey: "ground_beef_90_10",
    ingredientId: SEED_INGREDIENT_IDS.groundBeef9010,
    proteinFamily: "beef",
    displayName: "90/10 Ground Beef",
    species: "cattle",
    cut: "ground",
    form: "ground",
    boneState: "not_applicable",
    skinState: "not_applicable",
    fatDescriptor: "90/10",
    typicalPurchaseUnit: "lb",
    availabilityClass: "widely_available",
  }),
  product({
    id: SEED_PRODUCT_IDS.groundBeef937,
    canonicalKey: "ground_beef_93_7",
    ingredientId: SEED_INGREDIENT_IDS.groundBeef937,
    proteinFamily: "beef",
    displayName: "93/7 Ground Beef",
    species: "cattle",
    cut: "ground",
    form: "ground",
    boneState: "not_applicable",
    skinState: "not_applicable",
    fatDescriptor: "93/7",
    typicalPurchaseUnit: "lb",
    availabilityClass: "widely_available",
  }),
  product({
    id: SEED_PRODUCT_IDS.ribeyeSteak,
    canonicalKey: "beef_ribeye_steak",
    ingredientId: SEED_INGREDIENT_IDS.ribeyeSteak,
    proteinFamily: "beef",
    displayName: "Ribeye Steak",
    species: "cattle",
    cut: "ribeye",
    form: "steak",
    boneState: "boneless",
    skinState: "not_applicable",
    typicalPurchaseUnit: "lb",
    availabilityClass: "commonly_available",
  }),
  product({
    id: SEED_PRODUCT_IDS.nyStripSteak,
    canonicalKey: "beef_new_york_strip_steak",
    ingredientId: SEED_INGREDIENT_IDS.nyStripSteak,
    proteinFamily: "beef",
    displayName: "New York Strip Steak",
    species: "cattle",
    cut: "new_york_strip",
    form: "steak",
    boneState: "boneless",
    skinState: "not_applicable",
    typicalPurchaseUnit: "lb",
    availabilityClass: "commonly_available",
  }),
  product({
    id: SEED_PRODUCT_IDS.topSirloinSteak,
    canonicalKey: "beef_top_sirloin_steak",
    ingredientId: SEED_INGREDIENT_IDS.topSirloinSteak,
    proteinFamily: "beef",
    displayName: "Top Sirloin Steak",
    species: "cattle",
    cut: "top_sirloin",
    form: "steak",
    boneState: "boneless",
    skinState: "not_applicable",
    typicalPurchaseUnit: "lb",
    availabilityClass: "widely_available",
  }),
  product({
    id: SEED_PRODUCT_IDS.flankSteak,
    canonicalKey: "beef_flank_steak",
    ingredientId: SEED_INGREDIENT_IDS.flankSteak,
    proteinFamily: "beef",
    displayName: "Flank Steak",
    species: "cattle",
    cut: "flank",
    form: "steak",
    boneState: "boneless",
    skinState: "not_applicable",
    typicalPurchaseUnit: "lb",
    availabilityClass: "commonly_available",
  }),
  product({
    id: SEED_PRODUCT_IDS.beefTenderloin,
    canonicalKey: "beef_tenderloin",
    ingredientId: SEED_INGREDIENT_IDS.beefTenderloin,
    proteinFamily: "beef",
    displayName: "Beef Tenderloin",
    species: "cattle",
    cut: "tenderloin",
    form: "roast_or_steak",
    boneState: "boneless",
    skinState: "not_applicable",
    typicalPurchaseUnit: "lb",
    availabilityClass: "retailer_dependent",
  }),
  product({
    id: SEED_PRODUCT_IDS.chuckRoast,
    canonicalKey: "beef_chuck_roast",
    ingredientId: SEED_INGREDIENT_IDS.chuckRoast,
    proteinFamily: "beef",
    displayName: "Chuck Roast",
    species: "cattle",
    cut: "chuck",
    form: "roast",
    boneState: "boneless",
    skinState: "not_applicable",
    typicalPurchaseUnit: "lb",
    availabilityClass: "widely_available",
  }),
  product({
    id: SEED_PRODUCT_IDS.beefStewMeat,
    canonicalKey: "beef_stew_meat",
    ingredientId: SEED_INGREDIENT_IDS.beefStewMeat,
    proteinFamily: "beef",
    displayName: "Beef Stew Meat",
    species: "cattle",
    cut: "stew",
    form: "cubed",
    boneState: "boneless",
    skinState: "not_applicable",
    typicalPurchaseUnit: "lb",
    availabilityClass: "widely_available",
  }),
  product({
    id: SEED_PRODUCT_IDS.atlanticSalmonFillet,
    canonicalKey: "atlantic_salmon_fillet",
    ingredientId: SEED_INGREDIENT_IDS.atlanticSalmonFillet,
    proteinFamily: "fish",
    displayName: "Atlantic Salmon Fillet",
    species: "atlantic_salmon",
    cut: "fillet",
    form: "fillet",
    boneState: "boneless",
    skinState: "variable",
    typicalPurchaseUnit: "lb",
    availabilityClass: "commonly_available",
  }),
  product({
    id: SEED_PRODUCT_IDS.codFillet,
    canonicalKey: "cod_fillet",
    ingredientId: SEED_INGREDIENT_IDS.codFillet,
    proteinFamily: "fish",
    displayName: "Cod Fillet",
    species: "cod",
    cut: "fillet",
    form: "fillet",
    boneState: "boneless",
    skinState: "skinless",
    typicalPurchaseUnit: "lb",
    availabilityClass: "commonly_available",
  }),
  product({
    id: SEED_PRODUCT_IDS.tilapiaFillet,
    canonicalKey: "tilapia_fillet",
    ingredientId: SEED_INGREDIENT_IDS.tilapiaFillet,
    proteinFamily: "fish",
    displayName: "Tilapia Fillet",
    species: "tilapia",
    cut: "fillet",
    form: "fillet",
    boneState: "boneless",
    skinState: "skinless",
    typicalPurchaseUnit: "lb",
    availabilityClass: "widely_available",
  }),
  product({
    id: SEED_PRODUCT_IDS.shrimpPeeledDeveined,
    canonicalKey: "shrimp_raw_peeled_deveined",
    ingredientId: SEED_INGREDIENT_IDS.shrimpPeeledDeveined,
    proteinFamily: "shellfish",
    displayName: "Raw Peeled and Deveined Shrimp",
    species: "shrimp",
    cut: "tail_on_or_off",
    form: "peeled_deveined_raw",
    boneState: "not_applicable",
    skinState: "not_applicable",
    typicalPurchaseUnit: "lb",
    availabilityClass: "widely_available",
  }),
  product({
    id: SEED_PRODUCT_IDS.lobsterTail,
    canonicalKey: "lobster_tail",
    ingredientId: SEED_INGREDIENT_IDS.lobsterTail,
    proteinFamily: "shellfish",
    displayName: "Lobster Tail",
    species: "lobster",
    cut: "tail",
    form: "tail",
    boneState: "not_applicable",
    skinState: "not_applicable",
    typicalPurchaseUnit: "count",
    availabilityClass: "specialty",
  }),
  product({
    id: SEED_PRODUCT_IDS.largeChickenEggs,
    canonicalKey: "chicken_eggs_large",
    ingredientId: SEED_INGREDIENT_IDS.largeChickenEggs,
    proteinFamily: "egg",
    displayName: "Large Chicken Eggs",
    species: "chicken",
    cut: "whole_egg",
    form: "shell_egg",
    boneState: "not_applicable",
    skinState: "not_applicable",
    typicalPurchaseUnit: "count",
    availabilityClass: "widely_available",
  }),
  product({
    id: SEED_PRODUCT_IDS.paneer,
    canonicalKey: "paneer",
    ingredientId: SEED_INGREDIENT_IDS.paneer,
    proteinFamily: "paneer",
    displayName: "Paneer",
    form: "block",
    boneState: "not_applicable",
    skinState: "not_applicable",
    typicalPurchaseUnit: "oz",
    availabilityClass: "commonly_available",
  }),
  product({
    id: SEED_PRODUCT_IDS.extraFirmTofu,
    canonicalKey: "tofu_extra_firm",
    ingredientId: SEED_INGREDIENT_IDS.extraFirmTofu,
    proteinFamily: "tofu",
    displayName: "Extra-Firm Tofu",
    form: "extra_firm_block",
    boneState: "not_applicable",
    skinState: "not_applicable",
    typicalPurchaseUnit: "package",
    availabilityClass: "widely_available",
  }),
  product({
    id: SEED_PRODUCT_IDS.cannedChickpeas,
    canonicalKey: "chickpeas_canned",
    ingredientId: SEED_INGREDIENT_IDS.cannedChickpeas,
    proteinFamily: "legume",
    displayName: "Canned Chickpeas",
    form: "canned_drained",
    boneState: "not_applicable",
    skinState: "not_applicable",
    typicalPurchaseUnit: "package",
    availabilityClass: "widely_available",
  }),
  product({
    id: SEED_PRODUCT_IDS.cookedLentils,
    canonicalKey: "lentils_cooked",
    ingredientId: SEED_INGREDIENT_IDS.cookedLentils,
    proteinFamily: "legume",
    displayName: "Cooked Lentils",
    form: "cooked",
    boneState: "not_applicable",
    skinState: "not_applicable",
    typicalPurchaseUnit: "oz",
    availabilityClass: "widely_available",
  }),
];

export const SEED_INGREDIENT_ALIASES: IngredientAlias[] = [
  alias("c3000000-0000-4000-a000-000000000001", SEED_INGREDIENT_IDS.ribeyeSteak, "ribeye"),
  alias("c3000000-0000-4000-a000-000000000002", SEED_INGREDIENT_IDS.ribeyeSteak, "rib eye"),
  alias(
    "c3000000-0000-4000-a000-000000000003",
    SEED_INGREDIENT_IDS.ribeyeSteak,
    "ribeye steak",
  ),
  alias(
    "c3000000-0000-4000-a000-000000000004",
    SEED_INGREDIENT_IDS.chickenBreastBonelessSkinless,
    "boneless skinless chicken breast",
  ),
  alias(
    "c3000000-0000-4000-a000-000000000005",
    SEED_INGREDIENT_IDS.atlanticSalmonFillet,
    "atlantic salmon",
  ),
  alias(
    "c3000000-0000-4000-a000-000000000006",
    SEED_INGREDIENT_IDS.shrimpPeeledDeveined,
    "peeled deveined shrimp",
  ),
  alias(
    "c3000000-0000-4000-a000-000000000007",
    SEED_INGREDIENT_IDS.extraFirmTofu,
    "extra firm tofu",
  ),
];

/**
 * Terms that must not silently resolve to a single cut/fat ratio.
 * Alias resolution returns refinement_required when these are queried.
 */
export const AMBIGUOUS_ALIAS_TERMS: ReadonlyMap<string, readonly string[]> = new Map([
  [
    "ground beef",
    [
      SEED_INGREDIENT_IDS.groundBeef8020,
      SEED_INGREDIENT_IDS.groundBeef9010,
      SEED_INGREDIENT_IDS.groundBeef937,
    ],
  ],
  [
    "steak",
    [
      SEED_INGREDIENT_IDS.ribeyeSteak,
      SEED_INGREDIENT_IDS.nyStripSteak,
      SEED_INGREDIENT_IDS.topSirloinSteak,
      SEED_INGREDIENT_IDS.flankSteak,
    ],
  ],
  [
    "generic steak",
    [
      SEED_INGREDIENT_IDS.ribeyeSteak,
      SEED_INGREDIENT_IDS.nyStripSteak,
      SEED_INGREDIENT_IDS.topSirloinSteak,
      SEED_INGREDIENT_IDS.flankSteak,
    ],
  ],
]);

export const SEED_RETAILER_EVIDENCE: RetailerAvailabilityEvidence[] = [
  {
    id: "c4000000-0000-4000-a000-000000000001",
    proteinProductId: SEED_PRODUCT_IDS.chickenBreastBonelessSkinless,
    retailer: "costco",
    confidence: "likely",
    region: "US",
    productForm: "boneless skinless breast tray",
    notes: "Typically stocked in membership warehouse meat cases; not live inventory.",
  },
  {
    id: "c4000000-0000-4000-a000-000000000002",
    proteinProductId: SEED_PRODUCT_IDS.ribeyeSteak,
    retailer: "whole_foods",
    confidence: "likely",
    region: "US",
    productForm: "ribeye steak",
    notes: "Commonly offered in butcher case; confidence is not verified.",
  },
  {
    id: "c4000000-0000-4000-a000-000000000003",
    proteinProductId: SEED_PRODUCT_IDS.groundBeef8020,
    retailer: "walmart",
    confidence: "likely",
    region: "US",
    productForm: "80/20 ground beef",
  },
  {
    id: "c4000000-0000-4000-a000-000000000004",
    proteinProductId: SEED_PRODUCT_IDS.atlanticSalmonFillet,
    retailer: "trader_joes",
    confidence: "likely",
    region: "US",
    productForm: "atlantic salmon fillet",
  },
  {
    id: "c4000000-0000-4000-a000-000000000005",
    proteinProductId: SEED_PRODUCT_IDS.lobsterTail,
    retailer: "whole_foods",
    confidence: "unknown",
    region: "US",
    productForm: "lobster tail",
    notes: "Specialty seafood; coverage varies by store.",
  },
  {
    id: "c4000000-0000-4000-a000-000000000006",
    proteinProductId: SEED_PRODUCT_IDS.extraFirmTofu,
    retailer: "trader_joes",
    confidence: "verified",
    region: "US",
    productForm: "extra firm tofu",
    sourceUrl: "https://www.traderjoes.com/home/products/pdp/organic-sprouted-tofu-extra-firm-072169",
    verifiedAt: "2026-03-01T12:00:00.000Z",
    notes: "Product page evidence for a specific tofu form — not a homepage.",
  },
];

/** No approved cut↔cut substitutions in this story — directional sample only. */
export const SEED_SUBSTITUTIONS: IngredientSubstitution[] = [
  {
    id: "c5000000-0000-4000-a000-000000000001",
    sourceIngredientId: SEED_INGREDIENT_IDS.tilapiaFillet,
    substituteIngredientId: SEED_INGREDIENT_IDS.codFillet,
    compatibility: "recipe_dependent",
    notes: "Mild white fish swap may work in some preparations; not automatic.",
    approved: true,
  },
];

export type IngredientCatalogSnapshot = {
  ingredients: CanonicalIngredient[];
  proteinProducts: ProteinProduct[];
  aliases: IngredientAlias[];
  retailerEvidence: RetailerAvailabilityEvidence[];
  substitutions: IngredientSubstitution[];
};

export function createSeedCatalogSnapshot(): IngredientCatalogSnapshot {
  return {
    ingredients: SEED_CANONICAL_INGREDIENTS.map((row) => ({ ...row })),
    proteinProducts: SEED_PROTEIN_PRODUCTS.map((row) => ({ ...row })),
    aliases: SEED_INGREDIENT_ALIASES.map((row) => ({ ...row })),
    retailerEvidence: SEED_RETAILER_EVIDENCE.map((row) => ({ ...row })),
    substitutions: SEED_SUBSTITUTIONS.map((row) => ({ ...row })),
  };
}
